### ISSUE TITLE
scikit-image dependency  fails on OSX M1 chip

### ISSUE THREAD

**Issue by shaystrong** [iceye-ltd/icecube#10]
Can't install all requirements for icecube on an M1 chip. This may present a future problem, just documenting for awareness. `scikit-image` cannot seem to be compiled/installed/etc on the M1. I have not tested the conda installation, as perhaps that does work. But i use brew/pip (and conda can create conflicts with those)

**Comment by shaystrong** [comment]
turns out -- works perfect with a conda install! Problem solved, but still worth noting.

**Comment by muaali** [comment]
Thanks @shaystrong for bringing it to the notice. I will close the issue for now.
